language: java
env:
  global:
  - http_proxy=http://proxy.wdf.sap.corp:8080 HTTP_PROXY=http://proxy.wdf.sap.corp:8080
    https_proxy=http://proxy.wdf.sap.corp:8080 HTTPS_PROXY=http://proxy.wdf.sap.corp:8080
    ftp_proxy=http://proxy.wdf.sap.corp:8080 FTP_PROXY=http://proxy.wdf.sap.corp:8080
    no_proxy="*.local,169.254/16,*.sap.corp,*.corp.sap" NO_PROXY="*.local,169.254/16,*.sap.corp,*.corp.sap"
  - MAVEN_OPTS="-Dhttp.proxyHost=proxy.wdf.sap.corp -Dhttp.proxyPort=8080 -Dhttps.proxyHost=proxy.wdf.sap.corp
    -Dhttps.proxyPort=8080"
  - secure: NMQYJKXhwQbO49xAzkCVW5tDY20fF4u+uOpyeoJjXYXC4/QrSSoVkjTbkBFSa4UaHGaz5glWBvEafButscNdkCyYLtOTFSFzra/dvKHIxkYnlZ2jmCIMic3ecE8YAvonpcflg1EKarzJrrDIkQfzz0O059t7FoxlpENYL96bMdE= #MVN_USER
  - secure: D9OE4+E1tWwCxeO2q+aQ+Ig3d1RRnieHLOMOOvAtB9jwH1qse95liFY/BT2g5+RLWjruaU3Wrnd8C6uom+GgAlFiMsI1ucA73ebCgaYJEBd/8PcEMpqsCwJeykHqS52NUPFlaS6sE2wcUP9O2iHMayWgr1rWaCIK2ZkLO/zvygs= #MVN_PASSWORD
  - secure: bpYBGYaEiwUDgQ7YEJjDKDhQXJ67bXm3Yu9mZ5cy3m7/brlamNwsmQF1H1SsndaxEdPkC5XtKJP4iJIg7VwTQDBSYak8W8fwuP5Ajq7czE9lFDd068Bp2sjCIIKJu2PNDouCWBma0IPwzjJOeJQJgnBMGWiP6vwDcvFXGY3MK9M= #CF_USER
  - secure: OWnxMq6GhvdxVgB8cA1NT0fB42nPyKGTii5h+CR7qt2Kwv/uFJjDGwKmQUP0+77oYhNr4obzju7aG+FFS8zhAcaRr6pGS/k7CYA3yPrriuD9K50q/Z+M288Xcdgbjwtt3KmhGs4c43mV1PLWGjlsXTWQjzKMaG4C4F1WVW0+qso= #CF_PASSWORD
  - secure: EcMbSbBrsT2mh4xN8QYL422uzRLkVPPAiEcxKQWITPj8tU0gsEu60Vg4g+wFF64rCEtASMT2563yKInPvQUfj0ucQTC8eFgJoDBYxW2yNCUqQct0MHljhk67zwS9sziDa70bRHVlQATFv6z6mCoDx29KZKBwjziGqWZMMzp7eko= #YAAS_CLIENT_ID
  - secure: gkFL5IzvdspBitAmPDFa+JY7I5pZNoffVsHo5uw45uocaVIyfoEsJ04Oe39hqxKLuVwqfLfnFWpS57+2SNfinSmasSlSkXQIa7O8xVaa6a0LjAxxemWUcQ8C1UUN8T4SIiVtmeXY5MlXNOZ58v50fB6eozHQIOTnBtokz4l93jg= #YAAS_CLIENT_SECRET
  - secure: J4MIvRG03ZeoZyT4tyOcs/LvLDKWNuHd8ubF3s3Xqg5Nq+nh2P8c0PRnevXpR45pOkEngppSFPj6kEqVzSJigtq72wDQKZCYsoHPCF9G0gfLQWSeM1gE4D8MmeO7tpzdhJMzZeoSEa0qfQkuHYCg8PTD2JrNJhw276X/PFAPAg4= #YAAS_CLIENT
  - CF_ORG=sap_cec_prod
  - CF_APP=Java-Wishlist-v1
jdk:
- oraclejdk8
before_install:
- wget -O cf-linux-amd64.tgz "https://cli.run.pivotal.io/stable?release=linux64-binary&version=6.11.2&source=github-rel"
- tar xfz cf-linux-amd64.tgz
install:
- mvn install -DskipTests=true --settings settings.xml -Dhttp.proxyHost=proxy.wdf.sap.corp
  -Dhttp.proxyPort=8080 -Dhttps.proxyHost=proxy.wdf.sap.corp -Dhttps.proxyPort=8080
script:
- set -e # Break script section in case tests fail
- mvn test -B --settings settings.xml -Dmaven.install.skip=true -Dhttp.proxyHost=proxy.wdf.sap.corp
  -Dhttp.proxyPort=8080 -Dhttps.proxyHost=proxy.wdf.sap.corp -Dhttps.proxyPort=8080
- set +e # Perform upload in its entirety, even if part of it fails 
- sh upload.sh dev-manifest.yml
cache:
  directories:
  - $HOME/.m2
notifications:
  email:
    recipients:
    - sebastian.netuschil@sap.com
    on_success: always
